### ISSUE TITLE
efficeientsam support

### ISSUE THREAD

**Issue by zpge** [dinglufe/segment-anything-cpp-wrapper#46]
Can you add efficeientsam?

**Comment by ryouchinsa** [comment]
Thanks for your great script and we updated [Segment Anything CPP Wrapper for macOS](https://github.com/ryouchinsa/sam-cpp-macos) so that it corresponded to MobileSAM, EdgeSAM, EfficientSAM, HQ-SAM, and Segment Anything models.

Searching the "EfficientSAM" in our code, you can understand the difference to correspond to the EfficientSAM.
